services:
  # MySQL Master
  db-master:
    image: mysql:8.0
    container_name: commerce-db-master
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: commerce
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./master.cnf:/etc/mysql/conf.d/my.cnf
      - ./master-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # MySQL Replica
  db-replica:
    image: mysql:8.0
    container_name: commerce-db-replica
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: commerce
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-replica-data:/var/lib/mysql
      - ./replica.cnf:/etc/mysql/conf.d/my.cnf
      - ./replica-init:/replica-init
      - ./replica-entrypoint.sh:/usr/local/bin/replica-entrypoint.sh
    entrypoint: [ "/usr/local/bin/replica-entrypoint.sh" ]
    depends_on:
      db-master:
        condition: service_healthy
    networks:
      - app-network

  # Confluent Kafka with KRaft
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      # Kraft 설정
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      # 리스너 설정
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # 일반 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      # Kraft 클러스터 ID
      CLUSTER_ID: 'KafkaClusterId'
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - app-network

  # Cassandra with improved configuration
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"  # CQL native transport port
    environment:
      CASSANDRA_CLUSTER_NAME: "CommerceCluster"
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
      CASSANDRA_SEEDS: "cassandra"
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - app-network

volumes:
  mysql-master-data:
  mysql-replica-data:
  cassandra-data:
  kafka-data:

networks:
  app-network:
    driver: bridge
