services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: commerce-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: commerce
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

